### ISSUE TITLE
`./devel/download-latest` pulls the latest package regardless of label

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/conda-base#26]
### Current Behavior
`./devel/download-latest` pulls the latest package available regardless of the label, which can potentially result in package diffs with non-main packages for the CI release summary (see latest [example](https://github.com/nextstrain/conda-base/actions/runs/4937045705)). 

### Expected behavior
`./devel/download-latest` should only pull the latest `main` package.

**Comment by tsibley** [comment]
[Further discussion](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1683740433064829) happened in Slack.

Turns out this is an issue for Nextstrain CLI too.
