### ISSUE TITLE
macOS 10.14 cannot install any versions after `20230615T171309Z`

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/conda-base#38]
Found out that I could not install any versions after `20230615T171309Z` while investigating https://github.com/nextstrain/cli/issues/300. 

Traced this to the [update of `nodejs` in `20230628T211222Z` ](https://github.com/nextstrain/conda-base/actions/runs/5405903285/attempts/1#summary-14637705884) from version 18.15.0 to 18.16.1. 

The update of `nodejs` in https://github.com/conda-forge/nodejs-feedstock/pull/310 included bumping the minimum macOS version to 10.15.

**Comment by jameshadfield** [comment]
Nothing seems obvious in [the node changelog](https://nodejs.org/fr/blog/release/v18.16.0) why it coudn't be build on MacOS 10.14, but conda-forge [does indeed bump the minimum version to 10.15](https://github.com/conda-forge/nodejs-feedstock/pull/310/files#diff-92d4214334555338c6e098e1462e4dec3ca2032a9f2973bf5558d6b8c00503ceL20). 

I presume this doesn't include new docker containers @joverlee521, or do they fail on 10.14 as well?

I think we have to draw a line somewhere regarding how much we invest in compatibility for the cross-product of {runtimes, nextstrain/augur/auspice versions, OS/arch versions}, and I would be tempted to categorise this as "won't fix".

**Comment by tsibley** [comment]
The conda-forge recipe bump on macOS version appears at a glance to be to make the newer C11/C++17 `aligned_alloc()` function available via a paired Clang version bump. See [the error that was quoted](https://github.com/conda-forge/nodejs-feedstock/pull/310#issuecomment-1609355603).

macOS 10.14 went unsupported in October 2021. @joverlee521 It's probably time to upgrade since unsupported means no security updates!

**Comment by joverlee521** [comment]
Totally agree that we have to draw the line somewhere. I'm fine with closing this issue as "won't fix"!

I wonder if we want to add [run_constrained](https://github.com/conda-forge/nodejs-feedstock/blob/0bcbdb2c6d2fe12d651c57697fd9ba76c6a1c057/recipe/meta.yaml#L56) in our recipe.yaml similar to what [nodejs has in their recipe](https://github.com/conda-forge/nodejs-feedstock/blob/0bcbdb2c6d2fe12d651c57697fd9ba76c6a1c057/recipe/meta.yaml#L56). 

This at least provides a nice error message when I try to install nodejs with mamba:
```
$  mamba install -c conda-forge nodejs==18.16.1 --quiet
Could not solve for environment specs
The following packages are incompatible
├─ __osx is requested and can be installed;
└─ nodejs 18.16.1  is not installable because it requires
   └─ __osx >=10.15 , which conflicts with any installable versions previously reported.
```

Although, the error message is not as clear when I try to install with micromamba: 
```
$ micromamba install -c conda-forge nodejs==18.16.1 --quiet
critical libmamba Could not set URL (code: 14 - url = @)
```

**Comment by tsibley** [comment]
"not as clear" is quite an understatement…

**Comment by tsibley** [comment]
Is this a "won't fix" situation?
