### ISSUE TITLE
Different Augur versions between osx-64 and linux-64 subdirs

### ISSUE THREAD

**Issue by victorlin** [nextstrain/conda-base#39]
Today, I observed the conda-base equivalent of https://github.com/nextstrain/docker-base/issues/128. In the [build for 20230731T202813Z](https://github.com/nextstrain/conda-base/actions/runs/5719328680), `augur` was bumped to 22.2.0 for `osx-64` but not `linux-64`. Only on the subsequent [build for 20230731T212806Z](https://github.com/nextstrain/conda-base/actions/runs/5719822909) did `augur` get  bumped to 22.2.0 for `linux-64`.

### Possible solutions

- #23

**Comment by victorlin** [comment]
I'm not sure why this is happened, but it was a bit hard to tell this was the case. I first noticed this when a monkeypox CI run which relied on `augur=22.2.0` [failed](https://github.com/nextstrain/monkeypox/actions/runs/5719485359/job/15497484130) with `20230731T202813Z`. When I debugged on my Macbook using the same build, it pulled `augur=22.2.0`. Without realizing I was using a different subdir build, this was confusing. Only after looking into how the Conda runtime's environment is built did I realize what was going on.

**Comment by tsibley** [comment]
Interesting. The augur Conda package is noarch, so the Bioconda channel index shouldn't have different versions between osx-64 and linux-64. The 22.2.0 package was uploaded at `2023-07-31 20:08:01.949000+00:00`. So I guess our builds maybe fell on either side of the index update that included the new version?

**Comment by victorlin** [comment]
No mentions of this since it was reported 9 months ago. We haven't taken any action so it's still possible, but I'm closing for now.
