### ISSUE TITLE
CI: Transient failures during Micromamba installation

### ISSUE THREAD

**Issue by victorlin** [nextstrain/conda-base#56]
[Example CI error](https://github.com/nextstrain/conda-base/actions/runs/7560882852/job/20587875591#step:8:13):

```
/Users/runner/work/_temp/a940fd79-97b7-42b8-9ac9-4d8ecc52367a.sh: line 1: micromamba: command not found
Error: Process completed with exit code 127.
```

This happens because the "Install Micromamba" step shows:

```
curl: (6) Could not resolve host: micro.mamba.pm
```

### Possible solutions

- Cache the Micromamba installation

**Comment by victorlin** [comment]
> how often is this happening?

Noticeably often today ([2 failed prior attempts](https://github.com/nextstrain/conda-base/actions/runs/7560882852)), yesterday ([1 failed attempt](https://github.com/nextstrain/conda-base/actions/runs/7547837449)), and maybe some from last week, I can't remember...

**Comment by victorlin** [comment]
> I'd also think we should enable `pipefail` in this CI job so that it fails when `curl` fails, instead of continuing on.

Yes, I plan to add that to #57. I think we just need to remove the `fail-fast: false` on that job.

**Comment by corneliusroemer** [comment]
Yeah definitely happened last week as well: https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1705086793993819

Not sure why they picked "Saint Pierre and Miquelon" for their domain, is it possible that top level registrars are unreliable?

**Comment by victorlin** [comment]
This was only noticeable for those few days. Closing since all has been fine for a few months now.
