### ISSUE TITLE
IQtree is locked to v1.6 rather than something modern like v2.2

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/conda-base#7]
### Current Behavior

Currently both osx and linux lockfiles install IQtree v1.6.

One way we could end up with lower versions is if a package moved from conda-forge to bioconda. Then we're stuck with whatever the last version was that was in conda-forge.

**Comment by corneliusroemer** [comment]
Pinning to `iqtree >=2` seems to fix it

**Comment by tsibley** [comment]
Hmm. At the beginning of this year we explicitly _added_ pangolin and pangolearn to our Docker runtime (and our ambient runtime install instructions). This is why they're also in our Conda runtime here (defined by the `nextstrain-base` package). I think a proposal to remove them needs more consideration than was given above.

> We use Nextclade in place of pangolin/pangolearn etc

Is that a change from earlier this year?

> …which we probably should not use here due to their complicated dependencies.

Their deps are pretty unfriendly to coexistence, but I'm not sure it means we shoudn't use them.

**Comment by corneliusroemer** [comment]
IIRC, they were added before Nextclade could annotate pango lineages.

Back then, we thought it may be worth running Usher ourselves so we have up to date lineage annotations (there were some GISAID delays, and GISAID used pangoLEARN).

In the end, we never ran pangolin (Usher or pangoLEARN) in ncov-ingest.

Happy to hear feedback, whether anyone actually uses pangolin/pangoLEARN from our docker images/conda environment.

Not including Usher makes it not very practical though.

**Comment by tsibley** [comment]
Our ncov workflow still [nominally supports](https://github.com/nextstrain/ncov/pull/593) running Pangolin when the `run_pangolin` config flag is enabled. So I think the questions are:

1. Are we using that? (Sounds like not.)
2. Is anyone else using that? (Maybe CZI?)

**Comment by tsibley** [comment]
[Requested others to offer insight in Slack too](https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1670455328525079).

**Comment by tsibley** [comment]
I [found a few uses using GitHub Code Search](https://cs.github.com/?scopeName=All+repos&scope=&q=%2Frun_pangolin%5Cs*%5B%3A%3D%5D%2F):

- [pvanheus/ncov/blob/9a78c0d8/my_profiles/africa_recent_full/parameters.yaml](https://github.com/pvanheus/ncov/blob/9a78c0d8d60eeca5ed218b4cf2ebb3f1d9ae5959/my_profiles/africa_recent_full/parameters.yaml#L4)
- [blab/ncov-kenya/blob/2d1bac02/builds.yaml](https://github.com/blab/ncov-kenya/blob/2d1bac02fe09c061673f6c46063134d8e9654a3f/builds.yaml#L43)
- [phac-nml/SARS-CoV-2-resources/blob/216a165c/builds.yaml](https://github.com/phac-nml/SARS-CoV-2-resources/blob/216a165c85fe6ccfebfc33418d3bde582b9162d0/builds.yaml#L3)

As well as at least one indication of "dark" usage (e.g. usage we can't directly find):

- https://github.com/nextstrain/ncov/issues/829
