### ISSUE TITLE
Drop macos-11 from GH Action workflow

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/conda-base#72]
Totally missed all the announcements that GH Actions will be removing macos-11.

- [announcement back in January](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/)
- [announcement in May](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal)
- [macos-11 brownout on June 24](https://github.com/nextstrain/conda-base/actions/runs/9649963891)

**Comment by victorlin** [comment]
Based on https://github.com/search?q=org%3Anextstrain+"macos-11"&type=code, nextstrain/cli is the only other repo that uses `macos-11` across @nextstrain so we're good after https://github.com/nextstrain/cli/issues/375 is done
