### ISSUE TITLE
tsv-utils raises error in new installation

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/conda-base#75]
Error in [latest seasonal-flu CI](https://github.com/nextstrain/conda-base/actions/runs/9749555579/job/26907218757#step:8:138) from tsv-utils 

Detailed error in the logs of the [uploaded artifact for seasonal-flu](https://github.com/nextstrain/conda-base/actions/runs/9749555579/artifacts/1656770255)
```
tsv-append: error while loading shared libraries: libphobos2-ldc-shared.so.108: cannot open shared object file: No such file or directory
```

**Comment by joverlee521** [comment]
Seems related to https://github.com/conda-forge/tsv-utils-feedstock/pull/2

**Comment by joverlee521** [comment]
tsv-utils will run into errors for a new installation/update of conda-base 

```
$ nextstrain update conda
$ nextstrain shell --conda . 
$ tsv-select --version
dyld[16067]: Library not loaded: @rpath/libphobos2-ldc-shared.108.dylib
  Referenced from: <C97A2355-08EA-3753-8C54-F3855A65839E> /Users/joverlee/.nextstrain/runtimes/conda/env/bin/tsv-select
  Reason: tried: '/Users/joverlee/.nextstrain/runtimes/conda/env/bin/../lib/libphobos2-ldc-shared.108.dylib' (no such file), '/Users/joverlee/.nextstrain/runtimes/conda/env/bin/../lib/libphobos2-ldc-shared.108.dylib' (no such file), '/usr/local/lib/libphobos2-ldc-shared.108.dylib' (no such file), '/usr/lib/libphobos2-ldc-shared.108.dylib' (no such file, not in dyld cache)
Abort trap: 6
```

**Comment by corneliusroemer** [comment]
Retry with the latest conda-forge version, now ldc is added as a runtime requirement

**Comment by joverlee521** [comment]
[Running the CI](https://github.com/nextstrain/conda-base/actions/runs/9750215950) to pull in the latest conda-forge version

**Comment by joverlee521** [comment]
[Running the CI](https://github.com/nextstrain/conda-base/actions/runs/9750376852)

**Comment by joverlee521** [comment]
@corneliusroemer I'm still seeing the same error in the [latest seasonal-flu CI](https://github.com/nextstrain/conda-base/actions/runs/9750376852/job/26909998377#step:8:138) that's using the new build of tsv-utils from conda-forge.

**Comment by joverlee521** [comment]
> Also affecting [`seasonal-cov` CI](https://github.com/nextstrain/seasonal-cov/actions/runs/9751679629/job/26913776741?pr=24), I think?

Yeah, updated the title to reflect that tsv-utils will error in any workflow that uses a new installation of conda-base.

**Comment by joverlee521** [comment]
[Running CI again](https://github.com/nextstrain/conda-base/actions/runs/9752086971) to pull in latest build from conda-forge.

**Comment by corneliusroemer** [comment]
Fixed now, sorry for the disturbance here by moving tsv-utils around and starting with a bad recipe.

Now things should work again with the advantage that we'll have linux aarch64 and osx-arm64 builds of tsv-utils in conda soon :)
