### ISSUE TITLE
Reenable zika/mpox pathogen repo ci

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/conda-base#78]
This todo can now be done AFAICT

https://github.com/nextstrain/conda-base/blob/224ad3997cc7ca17fa6fa2ed29ade37c21b3fece/.github/workflows/ci.yaml#L149-L152

**Comment by joverlee521** [comment]
Related to https://github.com/nextstrain/.github/issues/94 and the bigger issue https://github.com/nextstrain/.github/issues/84
